### ISSUE TITLE
error: argument --ckey-value/-c: could not parse argument when using '>=2024.8.6' 

### ISSUE THREAD

**Issue by zedfmario** [PasaOpasen/toml-union#9]
Hi there, 

when running 
```shell
toml-union <file1> <file2> -o <output> -c tool.poetry.dependencies.package.version='>=2024.8.6' 
```
it fails with 

```text
usage: toml_union.py [-h] [--output OUTFILE] [--unicode-escape] [--report REPORT] [--remove-field [REMOVE_FIELDS ...]] [--key-value KEY=VALUE]
                     [--ckey-value KEY=VALUE]
                     INPUT [INPUT ...]
toml_union.py: error: argument --ckey-value/-c: could not parse argument "tool.poetry.dependencies.package.version=>=2024.8.6" as k=v format
```

It does work thought with `>` instead of `>=`

Any idea?

**Comment by zedfmario** [comment]
@PasaOpasen @clupuishere 

I hope you're doing well.

I wanted to check in on the status of issue #10. There's no rush, but I wanted to know if you plan to include it in the near future. This will help me decide whether to continue using the fork or switch back.

Thank you for your time!

**Comment by PasaOpasen** [comment]
@zedfmario fixed just now, update the package

**Comment by zedfmario** [comment]
thx
